version: '3'

services:
  web-commander:
    image: registry.cn-hangzhou.aliyuncs.com/devzyh/web-commander:latest

    container_name: web_commander
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./config.yml:/app/config.yml
